### ISSUE TITLE
3 & 4. Downloading and Combining Data CSV

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/DSCI525_group16#4]
We will all use Austin's code found in the notebook for downloading, extracting, and combining the data. 
Then post our machine specs and runtimes into the notebook.

eg. 

Team Member | Operating System | RAM | Processor | Is SSD | Time taken
-- | -- | -- | -- | -- | --
Renee | MacOS | 8GB | Dual-Core Intel Core i5 | Yes | 4min 38s

I can summarize our observations for this section.

**Comment by WilfHass** [comment]
Linking my PR #12 for easy access to my combining times!
